// Generated by view binder compiler. Do not edit!
package com.akmal.mygoldzakat.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akmal.mygoldzakat.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentHomeBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final ImageView copyright4;

  @NonNull
  public final TextView copyright5;

  @NonNull
  public final ImageView imageView2;

  @NonNull
  public final TextView textView;

  @NonNull
  public final TextView textView2;

  private FragmentHomeBinding(@NonNull FrameLayout rootView, @NonNull ImageView copyright4,
      @NonNull TextView copyright5, @NonNull ImageView imageView2, @NonNull TextView textView,
      @NonNull TextView textView2) {
    this.rootView = rootView;
    this.copyright4 = copyright4;
    this.copyright5 = copyright5;
    this.imageView2 = imageView2;
    this.textView = textView;
    this.textView2 = textView2;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentHomeBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_home, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentHomeBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.copyright4;
      ImageView copyright4 = ViewBindings.findChildViewById(rootView, id);
      if (copyright4 == null) {
        break missingId;
      }

      id = R.id.copyright5;
      TextView copyright5 = ViewBindings.findChildViewById(rootView, id);
      if (copyright5 == null) {
        break missingId;
      }

      id = R.id.imageView2;
      ImageView imageView2 = ViewBindings.findChildViewById(rootView, id);
      if (imageView2 == null) {
        break missingId;
      }

      id = R.id.textView;
      TextView textView = ViewBindings.findChildViewById(rootView, id);
      if (textView == null) {
        break missingId;
      }

      id = R.id.textView2;
      TextView textView2 = ViewBindings.findChildViewById(rootView, id);
      if (textView2 == null) {
        break missingId;
      }

      return new FragmentHomeBinding((FrameLayout) rootView, copyright4, copyright5, imageView2,
          textView, textView2);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
