// Generated by view binder compiler. Do not edit!
package com.akmal.mygoldzakat.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.FrameLayout;
import android.widget.ImageView;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.akmal.mygoldzakat.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class FragmentCalculateBinding implements ViewBinding {
  @NonNull
  private final FrameLayout rootView;

  @NonNull
  public final Button btnCalculateInput;

  @NonNull
  public final ImageView copyright1;

  @NonNull
  public final TextView copyright2;

  @NonNull
  public final EditText currentValueInput;

  @NonNull
  public final TextView goldValueOutput;

  @NonNull
  public final RadioButton keepRadioInput;

  @NonNull
  public final RadioGroup radioGroupInput;

  @NonNull
  public final TextView tajuk;

  @NonNull
  public final TextView ttlZakatOutput;

  @NonNull
  public final RadioButton wearRadioInput;

  @NonNull
  public final EditText weightInput;

  @NonNull
  public final TextView zakatPayableOutput;

  private FragmentCalculateBinding(@NonNull FrameLayout rootView, @NonNull Button btnCalculateInput,
      @NonNull ImageView copyright1, @NonNull TextView copyright2,
      @NonNull EditText currentValueInput, @NonNull TextView goldValueOutput,
      @NonNull RadioButton keepRadioInput, @NonNull RadioGroup radioGroupInput,
      @NonNull TextView tajuk, @NonNull TextView ttlZakatOutput,
      @NonNull RadioButton wearRadioInput, @NonNull EditText weightInput,
      @NonNull TextView zakatPayableOutput) {
    this.rootView = rootView;
    this.btnCalculateInput = btnCalculateInput;
    this.copyright1 = copyright1;
    this.copyright2 = copyright2;
    this.currentValueInput = currentValueInput;
    this.goldValueOutput = goldValueOutput;
    this.keepRadioInput = keepRadioInput;
    this.radioGroupInput = radioGroupInput;
    this.tajuk = tajuk;
    this.ttlZakatOutput = ttlZakatOutput;
    this.wearRadioInput = wearRadioInput;
    this.weightInput = weightInput;
    this.zakatPayableOutput = zakatPayableOutput;
  }

  @Override
  @NonNull
  public FrameLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static FragmentCalculateBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static FragmentCalculateBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.fragment_calculate, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static FragmentCalculateBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnCalculateInput;
      Button btnCalculateInput = ViewBindings.findChildViewById(rootView, id);
      if (btnCalculateInput == null) {
        break missingId;
      }

      id = R.id.copyright1;
      ImageView copyright1 = ViewBindings.findChildViewById(rootView, id);
      if (copyright1 == null) {
        break missingId;
      }

      id = R.id.copyright2;
      TextView copyright2 = ViewBindings.findChildViewById(rootView, id);
      if (copyright2 == null) {
        break missingId;
      }

      id = R.id.currentValueInput;
      EditText currentValueInput = ViewBindings.findChildViewById(rootView, id);
      if (currentValueInput == null) {
        break missingId;
      }

      id = R.id.goldValueOutput;
      TextView goldValueOutput = ViewBindings.findChildViewById(rootView, id);
      if (goldValueOutput == null) {
        break missingId;
      }

      id = R.id.keepRadioInput;
      RadioButton keepRadioInput = ViewBindings.findChildViewById(rootView, id);
      if (keepRadioInput == null) {
        break missingId;
      }

      id = R.id.radioGroupInput;
      RadioGroup radioGroupInput = ViewBindings.findChildViewById(rootView, id);
      if (radioGroupInput == null) {
        break missingId;
      }

      id = R.id.tajuk;
      TextView tajuk = ViewBindings.findChildViewById(rootView, id);
      if (tajuk == null) {
        break missingId;
      }

      id = R.id.ttlZakatOutput;
      TextView ttlZakatOutput = ViewBindings.findChildViewById(rootView, id);
      if (ttlZakatOutput == null) {
        break missingId;
      }

      id = R.id.wearRadioInput;
      RadioButton wearRadioInput = ViewBindings.findChildViewById(rootView, id);
      if (wearRadioInput == null) {
        break missingId;
      }

      id = R.id.weightInput;
      EditText weightInput = ViewBindings.findChildViewById(rootView, id);
      if (weightInput == null) {
        break missingId;
      }

      id = R.id.zakatPayableOutput;
      TextView zakatPayableOutput = ViewBindings.findChildViewById(rootView, id);
      if (zakatPayableOutput == null) {
        break missingId;
      }

      return new FragmentCalculateBinding((FrameLayout) rootView, btnCalculateInput, copyright1,
          copyright2, currentValueInput, goldValueOutput, keepRadioInput, radioGroupInput, tajuk,
          ttlZakatOutput, wearRadioInput, weightInput, zakatPayableOutput);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
